Desktop/warehouse_management/login_whm/urls.py
from django.urls import path
from . import views


app_name = 'login_whm'


urlpatterns = [
    path('', views.user_login, name='user_login'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('logout/', views.user_logout, name='logout'),
    path('sign_up_success/', views.sign_up_success, name='sign_up_success'),
]

Desktop/warehouse_management/warehouse_m/urls.py
from django.urls import path
from . import views


app_name = 'warehouse_m'


urlpatterns = [
    path('index/', views.Index.as_view(), name='index'),
    path('results/', views.search_index, name='search_index'),
    path('update/<pk>', views.UpdateProduct.as_view(), name='update'),
    path('create', views.CreateProduct.as_view(), name='create'),
    path('delete/<pk>', views.DeleteProduct.as_view(), name='delete'),
]

Desktop/warehouse_management/warehouse_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login_whm.urls', namespace='login_whm')),
    path('warehouse/', include('warehouse_m.urls', namespace='warehouse_m')),
]

Desktop/warehouse_management/login_whm/models.py
from django.db import models

Desktop/warehouse_management/warehouse_m/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Product(models.Model):
    category = models.CharField(max_length=128)
    manufacturer = models.CharField(max_length=64)
    code = models.CharField(max_length=64)
    product = models.CharField(max_length=256)
    price = models.FloatField()
    warranty = models.IntegerField()

    def __str__(self):
        return f'{self.category} {self.product} {self.price}'

    def get_absolute_url(self):
        return reverse('warehouse_m:index')

Desktop/warehouse_management/login_whm/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserLoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'email')


class UserCreateForm(UserCreationForm):
    password1 = forms.CharField(label="Password",
                                widget=forms.PasswordInput(attrs={'class': 'input'}))
    password2 = forms.CharField(label="Password confirmation",
                                widget=forms.PasswordInput(attrs={'class': 'input'}),
                                help_text="Enter the same password as above, for verification.")

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'input'}),
            'email': forms.TextInput(attrs={'class': 'input'}),
            'first_name': forms.TextInput(attrs={'class': 'input'}),
            'last_name': forms.TextInput(attrs={'class': 'input'}),
        }

Desktop/warehouse_management/warehouse_m/forms.py
from django import forms
from .models import Product


class PaginateOrAll(forms.Form):
    show = forms.ModelChoiceField(queryset=['PAGINATE', 'ALL PRODUCTS'])

Desktop/warehouse_management/login_whm/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from .forms import UserCreateForm
from django.core.mail import send_mail


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['pass']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('warehouse_m:index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE!')

    return render(request, 'login_whm/user_login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login_whm:user_login'))


def sign_up(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            sender = form.cleaned_data['email']
            message = f"Username: {form.cleaned_data['username']} \n" \
                      f"Password: {form.cleaned_data['password1']} \n" \
                      f"First Name: {form.cleaned_data['first_name']} \n" \
                      f"Last Name: {form.cleaned_data['last_name']} \n" \
                      f"Email: {form.cleaned_data['email']}"
            send_mail("Waiting for approval!", message, sender, ['django.test.email2021@gmail.com'])
            return HttpResponseRedirect(reverse('login_whm:sign_up_success'))
    else:
        form = UserCreateForm()
    return render(request, 'login_whm/sign_up.html', {'form': form})


def sign_up_success(request):
    return render(request, 'login_whm/sign_up_success.html')

Desktop/warehouse_management/warehouse_m/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Product
from django.db.models import Q


class Index(ListView):

    model = Product
    template_name = 'warehouse_m/index.html'

    # fetch all products
    queryset = Product.objects.all()
    context_object_name = 'products'
    paginate_by = 8



def search_index(request):
    if request.method == 'POST':
        query = request.POST['search']
        # Search by manufacturer, category or the code of the product
        result = Product.objects.filter(Q(manufacturer__icontains=query) | Q(category__icontains=query) |
                                        Q(code__icontains=query))
        return render(request, 'warehouse_m/search.html', {'result': result})
    return HttpResponseRedirect(reverse('warehouse_m:index'))


class UpdateProduct(UpdateView):
    model = Product
    fields = '__all__'


class CreateProduct(CreateView):
    model = Product
    fields = '__all__'


class DeleteProduct(DeleteView):
    model = Product
    success_url = reverse_lazy('warehouse_m:index')

Desktop/warehouse_management/login_whm/templates/login_whm/sign_up.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
    <link rel="stylesheet" href="{% static 'login_whm/css/login_form.css' %}" />
</head>
<body>
<form action="{% url 'login_whm:sign_up' %}" method="post">
    {% csrf_token %}
<div class="login-wrap" style="background: url({% static 'login_whm/images/warehouse.jpg' %}) no-repeat center;">
	<div class="login-html">
		<input id="tab-1" type="radio" name="tab" class="sign-in" ><label for="tab-1" class="tab"></label>
		<input id="tab-2" type="radio" name="tab" class="sign-up" checked><label for="tab-2" class="tab">Sign Up</label>
		<div class="login-form">
			<div class="sign-up-htm">
				<div class="group">
					<label for="user" class="label">Username</label>
					{{ form.username }}
				</div>
				<div class="group">
					<label for="pass" class="label">Password</label>
                    {{ form.password1 }}
				</div>
				<div class="group">
					<label for="pass" class="label">Repeat Password</label>
                    {{ form.password2 }}
				</div>
				<div class="group">
					<label for="pass" class="label">Email Address</label>
                    {{ form.email }}
				</div>
                <div class="group">
					<label for="first_name" class="label">First Name</label>
                    {{ form.first_name }}
				</div>
                <div class="group">
					<label for="last_name" class="label">Last Name</label>
                    {{ form.last_name }}
				</div>
				<div class="group">
					<input type="submit" class="button" value="Sign Up">
                    <div style="text-align: center; color: white;"><a href="{% url 'login_whm:user_login' %}">
                        BACK</a></div>
				</div>
				<div class="hr"></div>


			</div>
		</div>
	</div>
</div>
    </form>
</body>
</html>

Desktop/warehouse_management/login_whm/templates/login_whm/sign_up_success.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
   <label class="display-2" style="text-align: justify">
       You have successfully signed up,
       but you must wait for the Administrator to approve your account. You'll get report on your email.
       <br><br>Thank you for your understanding.
   </label><br><br>
   <div style="text-align: center">
 <a  href="{% url 'login_whm:user_login' %}">
 <button type="button" class="btn btn-primary btn-lg">BACK</button></a></div>
  </body>
</html>

Desktop/warehouse_management/login_whm/templates/login_whm/user_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'login_whm/css/login_form.css' %}" />
</head>
<body>
<form action="{% url 'login_whm:user_login' %}" method="post">
    {% csrf_token %}
<div class="login-wrap" style="background: url({% static 'login_whm/images/warehouse.jpg' %}) no-repeat center;">
	<div class="login-html">
		<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>
		<input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab"></label>
		<div class="login-form">
			<div class="sign-in-htm">
				<div class="group">
					<label for="user" class="label">Username</label>
					<input id="user" name="username" type="text" class="input">
				</div>
				<div class="group">
					<label for="pass" class="label">Password</label>
					<input id="pass" name="pass" type="password" class="input" data-type="password">
				</div>

				<div class="group">
					<input type="submit" class="button" value="Sign In">
				</div>
				<div class="hr"></div>
				<div class="foot-lnk">
					<a href="#forgot">Forgot Password?</a><br><br>
                    <a href="{% url 'login_whm:sign_up' %}">Sign Up</a>
				</div>
			</div>

				<div class="hr"></div>

			</div>
		</div>
	</div>
</div>
    </form>
</body>
</html>

Desktop/warehouse_management/warehouse_m/templates/warehouse_m/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
{% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
  {% block content %}
  {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>


    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

Desktop/warehouse_management/warehouse_m/templates/warehouse_m/index.html
{% extends 'warehouse_m/base.html' %}
{% load mathfilters %}
{% block head %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
  /* Style the input field */
  #myInput {
    padding: 20px;
    margin-top: -6px;
    border: 0;
    border-radius: 0;
    background: #f1f1f1;
  }
  </style>
{% endblock %}
{% block title %}
    Index
{% endblock %}
{% block content %}

    <form action="{% url 'warehouse_m:search_index' %}" method="post">
      {% csrf_token %}
        <div class="input-group mb-3">
            <input type="text"  name="search" placeholder="Search">
            <input class="btn btn-success" type="submit" value="search">

        </div>


  </form>
  <div align="center">  <a href="{% url 'warehouse_m:create' %}" class="btn btn-primary">INSERT NEW PRODUCT</a></div>
<table class="table table-striped">
    <thead>
    <th>CATEGORY    {{ p.category }}</th>
    <th>MANUFACTURER</th>
    <th>CODE</th>
    <th>PRODUCT</th>
    <th>PRICE</th>
    <th>WARRANTY</th>
    <th></th><th></th>
    </thead>
    {% for product in products %}
        {% if forloop.counter0|divisibleby:2 %}
            <tr class="table-striped">
                <td>{{ product.category }}</td>
                <td>{{ product.manufacturer }}</td>
                <td>{{ product.code }}</td>
                <td>{{ product.product }}</td>
                <td>{{ product.price|div:52.6|floatformat:2 }}$</td>
                <td>{{ product.warranty }}</td>
                <td><a class="btn btn-warning" href="{% url 'warehouse_m:update' pk=product.pk %}">Update</a></td>
                <td><a class="btn btn-danger" href="{% url 'warehouse_m:delete' pk=product.pk %}">Delete</a></td>
            </tr>
        {% else %}
             <tr class="table-striped">
                <td>{{ product.category }}</td>
                <td>{{ product.manufacturer }}</td>
                <td>{{ product.code }}</td>
                <td>{{ product.product }}</td>
                <td>{{ product.price|div:52.6|floatformat:2 }}$</td>
                <td>{{ product.warranty }}</td>
                <td><a class="btn btn-warning" href="{% url 'warehouse_m:update' pk=product.pk %}">Update</a></td>
                <td><a class="btn btn-danger" href="{% url 'warehouse_m:delete' pk=product.pk %}">Delete</a></td>
            </tr>
        {% endif %}


    {% endfor %}
<tr><td colspan="8" align="center">
    {% if is_paginated %}
<div class="pagination">
<span>
{% if page_obj.has_previous %}
<a href="{% url "warehouse_m:index" %}?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}
<span style="margin-left:15px;margin-right:15px;">
Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
</span>
{% if page_obj.has_next %}
<a href="{% url "warehouse_m:index" %}?page={{ page_obj.next_page_number }}">Next</a>
{% endif %}
</span>
</div>
{% endif %}

</table>

 <script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $(".dropdown-menu li").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
{% endblock %}

Desktop/warehouse_management/warehouse_m/templates/warehouse_m/product_confirm_delete.html
{% extends 'warehouse_m/base.html' %}
{% block title %}Delete{% endblock %}
{% block content %}
    <form method="post">
      {% csrf_token %}
    <table class="table table-hover">
        <tr><td align="center"><h3>DELETE:</h3></td><td align="center">{{ product.category }}</td><td align="center">{{ product.code }}</td><td align="center">{{ product.product }}</td></tr>
        <tr>
            <td colspan="4" align="center">
                <input class="btn btn-danger" type="submit" value="DELETE">
                <a class="btn btn-warning" href="{% url 'warehouse_m:search_index' %}">CANCEL</a>
            </td>
        </tr>
    </table>
      </form>
{% endblock %}

Desktop/warehouse_management/warehouse_m/templates/warehouse_m/product_form.html
{% extends 'warehouse_m/base.html' %}
{% block title %}
    {% if not form.instance.pk %}
            Create
    {% else %}
            Update
    {% endif %}
{%endblock%}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <table class="table table-dark table-striped">

            <tr>
                <td align="right">Category</td><td>{{ form.category }}</td>
            </tr>
            <tr>
                <td align="right">Manufacturer</td><td>{{ form.manufacturer }}</td>
            </tr>
            <tr>
                <td align="right">Code</td><td>{{ form.code }}</td>
            </tr>
            <tr>
                <td align="right">Product</td><td>{{ form.product }}</td>
            </tr>
            <tr>
                <td align="right">Price</td><td>{{ form.price }}</td>
            </tr>
            <tr>
                <td align="right">Warranty</td><td>{{ form.warranty }}</td>
            </tr>

        <tr>
        <td></td>
        <td>
                {% if not form.instance.pk %}
        <input type="submit" class="btn btn-primary" value="CREATE">
        {% else %}
        <input type="submit" class="btn btn-warning" value="UPDATE">
        {% endif %}
            <a class="btn btn-warning" href="{% url 'warehouse_m:index' %}">CANCEL</a>
            </td>

        </tr>

        </table>
    </form>

{% endblock %}

Desktop/warehouse_management/warehouse_m/templates/warehouse_m/search.html
{% extends 'warehouse_m/base.html' %}
{% load mathfilters %}
{% block title %}Results{% endblock %}
{% block content %}
    <table class="table table-striped">
    <thead>
    <th>CATEGORY</th>
    <th>MANUFACTURER</th>
    <th>CODE</th>
    <th>PRODUCT</th>
    <th>PRICE</th>
    <th>WARRANTY</th>
    <th>IMAGE</th>
    <th></th><th></th>
    </thead>
    {% for res in result %}
        {% if forloop.counter0|divisibleby:2 %}
            <tr class="table-striped">
                <td>{{ res.category }}</td>
                <td>{{ res.manufacturer }}</td>
                <td>{{ res.code }}</td>
                <td>{{ res.product }}</td>
                 <td>{{ res.price|div:52.6|floatformat:2 }}$</td>
                <td>{{ res.warranty }}</td>
                 <td>{{ res.image }}</td>
                <td><a class="btn btn-warning" href="{% url 'warehouse_m:update' pk=res.pk %}">Update</a></td>
                <td><a class="btn btn-danger" href="{% url 'warehouse_m:delete' pk=res.pk %}">Delete</a></td>
            </tr>
        {% else %}
             <tr class="table-striped">
                <td>{{ res.category }}</td>
                <td>{{ res.manufacturer }}</td>
                <td>{{ res.code }}</td>
                <td>{{ res.product }}</td>
                 <td>{{ res.price|div:52.6|floatformat:2 }}$</td>
                <td>{{ res.warranty }}</td>
                  <td>{{ res.image }}</td>
                <td><a class="btn btn-warning" href="{% url 'warehouse_m:update' pk=res.pk %}">Update</a></td>
                <td><a class="btn btn-danger" href="{% url 'warehouse_m:delete' pk=res.pk %}">Delete</a></td>
            </tr>
        {% endif %}
    {% endfor %}
    </table>
{% endblock %}